version: '2'
services:
  exam-app:
    image: exam
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://exam-postgresql:5432/Exam
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  exam-postgresql:
    extends:
      file: postgresql.yml
      service: exam-postgresql
